<a href="https://colab.research.google.com/github/treekeaw1/-mana-bento-web/blob/main/Untitled41.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from io import StringIO

# แก้ไข: รวมข้อมูล CSV ทั้งหมดให้อยู่ใน string เดียวกัน และลบข้อความที่ไม่ใช่ข้อมูลออก
csv_content = """
วันที่,รางวัลที่ 1 (6 หลัก),เลข 2 ตัวล่าง
2025/06/01,559352,20
2025/05/16,251309,87
2025/05/02,213388,06
2025/04/16,266227,85
2025/04/01,669687,36
2025/03/16,757563,32
2025/03/01,818894,54
2025/02/16,847377,50
2025/02/01,558700,51
2025/01/17,807779,23
2025/01/02,730209,51
2024/12/16,097863,21
2024/12/01,669843,61
2024/11/16,187221,38
2024/11/01,536044,32
2024/10/16,482962,00
2024/10/01,718665,59
2024/09/16,608662,37
2024/09/01,199606,94
2024/08/16,095867,28
2024/08/01,407041,46
2024/07/16,367336,21
2024/07/01,434503,89
2024/06/16,518504,31
2024/06/01,530593,42
2024/05/16,205690,60
2024/05/02,980116,17
2024/04/16,943598,79
2024/04/01,803481,90
2024/03/16,997626,78
2024/03/01,253603,79
2024/02/16,941395,43
2024/02/01,607063,09
2024/01/17,105979,61
2023/12/30,625544,89
2023/12/16,356757,85
2023/12/01,251097,91
2023/11/16,557990,14
2023/11/01,743951,63
2023/10/16,931446,44
2023/10/01,727202,66
2023/09/16,320812,46
2023/09/01,915478,91
2023/08/16,471782,67
2023/08/01,407041,46
2023/07/31,260453,11
2023/07/16,169530,62
2023/07/01,922605,16
2023/06/16,264872,30
2023/06/01,125272,09
2023/05/16,132903,99
2023/05/02,843019,65
2023/04/16,984906,71
2023/04/01,087907,99
2023/03/16,025873,73
2023/03/01,417652,55
2023/02/16,590417,80
2023/02/01,297411,92
2023/01/17,812519,47
2022/12/30,157196,58
2022/12/16,845093,14
2022/12/01,375805,08
2022/11/16,121789,64
2022/11/01,913106,70
2022/10/16,613106,15
2022/10/01,484669,50
2022/09/16,943703,75
2022/09/01,929332,83
2022/08/16,331583,42
2022/08/01,436594,14
2022/07/16,620405,53
2022/07/01,981417,61
2022/06/16,361807,92
2022/06/01,319196,02
2022/05/16,155012,06
2022/05/02,658642,09
2022/04/16,395919,58
2022/04/01,970618,10
2022/03/16,737867,03
2022/03/01,061905,07
2022/02/17,098597,57
2022/02/01,944308,30
2022/01/17,880159,92
2021/12/30,819068,36
2021/12/16,639235,83
2021/12/01,077258,82
2021/11/16,032761,57
2021/11/01,045037,95
2021/10/16,386372,38
2021/10/01,578171,83
2021/09/16,070935,90
2021/09/01,114475,79
2021/08/16,046750,23
2021/08/01,910261,69
2021/07/16,556725,70
2021/07/01,713517,29
2021/06/16,691861,17
2021/06/01,292972,45
2021/05/16,684579,14
2021/05/02,501272,18
2021/04/16,100787,56
2021/04/01,472270,05
2021/03/16,890422,19
2021/03/01,835538,73
2021/02/16,424603,39
2021/02/01,912307,97
2021/01/17,384395,15
2020/12/30,803628,19
2020/12/16,201303,70
2020/12/01,100994,84
2020/11/16,972661,46
2020/11/01,506404,40
2020/10/16,286051,38
2020/10/01,837893,59
2020/09/16,244083,57
2020/09/01,999997,98
2020/08/16,945811,88
2020/08/01,569391,92
2020/07/16,873286,53
2020/07/01,347258,83
2020/06/16,516967,64
2020/06/01,831567,24
2020/04/01,051095,22
2020/03/16,503446,77
2020/03/01,875938,98
2020/02/16,781403,94
2020/02/01,589227,06
2020/01/17,491774,68
2019/12/30,510541,81
2019/12/16,529924,97
2019/12/01,453522,81
2019/11/16,017223,32
2019/11/01,967375,79
2019/10/16,812564,15
2019/10/01,691197,59
2019/09/16,340388,85
2019/09/01,798787,20
2019/08/16,775476,89
2019/08/01,387006,58
2019/07/15,369765,88
2019/07/01,943647,86
2019/06/16,174055,29
2019/06/01,516461,46
2019/05/16,962526,71
2019/05/02,061324,25
2019/04/16,570331,23
2019/04/01,109767,52
2019/03/16,724628,64
2019/03/01,345650,65
2019/02/16,074824,56
2019/02/01,967134,04
2019/01/17,197079,65
2018/12/30,735867,02
2018/12/16,356564,62
2018/12/01,021840,67
2018/11/16,989903,16
2018/11/01,149840,58
2018/10/16,200515,93
2018/10/01,452643,99
2018/09/16,149760,79
2018/09/01,734510,26
2018/08/16,586117,10
2018/08/01,386602,78
2018/07/16,596324,27
2018/07/01,963623,83
2018/06/16,223131,46
2018/06/01,988117,95
2018/05/16,075629,20
2018/05/02,248038,85
2018/04/16,739229,60
2018/04/01,412073,85
2018/03/16,218559,82
2018/03/02,759415,29
2018/02/16,309915,39
2018/02/01,026853,31
2018/01/17,203823,50
2017/12/30,911234,98
2017/12/16,955596,89
2017/12/01,451005,33
2017/11/16,292391,98
2017/11/01,533726,85
2017/10/16,413494,86
2017/10/01,880714,52
2017/09/16,170143,71
2017/09/01,143224,65
2017/08/16,715431,37
2017/08/01,756519,36
2017/07/16,820327,87
2017/07/01,112360,26
2017/06/16,943142,47
2017/06/01,053630,61
2017/05/16,454891,53
2017/05/02,008656,35
2017/04/16,816729,40
2017/04/01,392785,80
2017/03/16,273863,92
2017/03/01,978453,78
2017/02/16,229116,14
2017/02/01,054672,42
2017/01/17,145157,25
2016/12/30,377712,46
2016/12/16,435286,35
2016/12/01,086069,77
2016/11/16,858383,44
2016/11/01,785438,86
2016/10/16,571947,98
2016/10/01,887102,33
2016/09/16,240650,42
2016/09/01,638684,62
2016/08/16,254004,33
2016/08/01,272932,57
2016/07/16,449764,55
2016/07/01,082460,53
2016/06/16,073816,79
2016/06/01,511825,14
2016/05/16,141737,98
2016/05/02,399459,02
2016/04/16,221609,87
2016/04/01,066720,92
2016/03/16,134918,32
2016/03/01,439686,06
2016/02/16,356364,98
2016/02/01,927800,09
2016/01/17,304371,50
2015/12/30,008217,02
2015/12/17,930255,08
2015/12/01,915350,78
2015/11/16,795283,03
2015/11/01,361211,45
2015/10/16,968630,62
2015/10/01,594825,07
2015/09/16,743148,06
2015/09/01,021094,89
2015/08/16,033363,40
2015/08/01,518677,53
2015/07/16,121507,49
2015/07/01,759049,26
2015/06/16,644742,05
2015/06/02,388881,65
2015/05/16,011421,38
2015/05/02,543466,30
2015/04/16,506260,38
2015/04/01,605704,70
2015/03/16,048151,92
2015/03/01,240237,34
2015/02/16,001864,90
2015/02/01,155537,79
2015/01/16,244351,74
2014/12/30,461704,57
2014/12/16,948354,90
2014/12/01,480449,11
2014/11/16,479804,25
2014/11/01,206608,44
2014/10/16,656409,94
2014/10/01,375615,44
2014/09/16,772269,35
2014/09/01,856763,22
2014/08/16,662842,91
2014/08/01,766391,82
2014/07/16,468728,45
2014/07/01,378477,39
2014/06/16,673920,95
2014/06/01,781198,18
2014/05/16,087523,20
2014/05/02,103297,52
2014/04/16,153406,26
2014/04/01,028866,95
2014/03/16,531404,79
2014/03/01,906318,35
2014/02/16,384245,01
2014/02/01,180149,95
2014/01/16,306902,52
2013/12/30,561072,48
2013/12/16,341767,79
2013/12/01,168795,27
2013/11/16,806925,28
2013/11/01,739804,47
2013/10/16,963289,60
2013/10/01,647882,14
2013/09/16,562684,63
2013/09/01,548123,05
2013/08/16,321327,20
2013/08/01,356435,82
2013/07/16,566996,86
2013/07/01,646905,51
2013/06/16,289673,69
2013/06/01,935489,90
2013/05/16,687125,56
2013/05/02,603458,07
2013/04/16,843846,86
2013/04/01,571688,53
2013/03/16,968433,52
2013/03/01,976241,37
2013/02/16,368257,09
2013/02/01,565566,66
2013/01/16,820981,08
2012/12/30,302358,00
2012/12/16,529524,72
2012/12/01,110443,43
2012/11/16,639500,15
2012/11/01,524694,63
2012/10/16,281343,28
2012/10/01,124025,58
2012/09/16,540143,79
2012/09/01,329997,07
2012/08/16,683877,28
2012/08/01,895590,50
2012/07/16,904050,11
2012/07/01,915900,60
2012/06/16,159373,51
2012/06/01,882727,38
2012/05/16,814418,31
2012/05/02,889501,29
2012/04/16,583470,62
2012/04/01,257562,69
2012/03/16,607064,08
2012/03/01,222518,79
2012/02/16,648684,18
2012/02/01,320605,32
2012/01/16,451445,81
2011/12/30,526402,65
2011/12/16,884178,21
2011/12/01,408147,02
2011/11/16,997777,57
2011/11/01,805540,54
2011/10/16,955756,83
2011/10/01,511052,15
2011/09/16,731198,28
2011/09/01,724533,85
2011/08/16,536960,62
2011/08/01,218756,12
2011/07/16,116556,12
2011/07/01,622953,51
2011/06/16,351276,88
2011/06/01,562370,46
2011/05/16,406417,05
2011/05/02,054136,85
2011/04/16,825988,44
2011/04/01,814931,01
2011/03/16,593331,96
2011/03/01,656037,97
2011/02/16,481746,27
2011/02/01,610089,55
2011/01/16,281062,23
2010/12/30,884112,49
2010/12/16,334380,24
2010/12/01,181752,09
2010/11/16,813993,43
2010/11/01,191100,59
2010/10/16,621377,42
2010/10/01,488372,02
2010/09/16,017422,66
2010/09/01,354656,11
2010/08/16,911097,64
2010/08/01,210008,10
2010/07/16,180387,34
2010/07/01,480239,68
2010/06/16,500104,73
2010/06/01,444874,81
2010/05/16,480012,12
2010/05/02,360371,06
2010/04/16,211743,96
2010/04/01,959517,22
2010/03/16,364222,97
2010/03/01,215227,97
2010/02/16,133707,03
2010/02/01,186312,14
2010/01/16,073577,67
2009/12/30,994304,87
2009/12/16,685141,05
2009/12/01,776980,59
2009/11/16,055986,58
2009/11/01,689140,85
2009/10/16,258487,00
2009/10/01,169387,06
2009/09/16,202912,48
2009/09/01,015865,32
2009/08/16,462933,96
2009/08/01,154986,92
2009/07/16,000816,94
2009/07/01,207542,66
2009/06/16,930456,15
2009/06/01,777661,26
2009/05/16,111411,54
2009/05/02,294452,11
2009/04/16,368415,33
2009/04/01,816578,50
2009/03/16,268812,36
2009/03/01,553091,67
2009/02/16,038730,93
2009/02/01,534533,69
2009/01/16,743212,25
2008/12/30,218596,22
2008/12/16,074114,25
2008/12/01,205434,05
2008/11/16,002612,20
2008/11/01,272028,76
2008/10/16,431277,98
2008/10/01,882911,67
2008/09/16,012377,56
2008/09/01,695993,09
2008/08/16,380377,36
2008/08/01,850348,11
2008/07/16,257374,41
2008/07/01,943671,50
2008/06/16,729111,75
2008/06/01,414875,35
2008/05/16,329231,69
2008/05/02,453011,62
2008/04/16,982800,64
2008/04/01,012653,71
2008/03/16,074946,33
2008/03/01,936685,05
2008/02/16,137054,80
2008/02/01,212684,26
2008/01/16,556010,81
2007/12/30,595411,81
2007/12/16,513501,96
2007/12/01,113410,18
2007/11/16,562481,73
2007/11/01,927907,88
2007/10/16,032988,48
2007/10/01,430667,76
2007/09/16,499336,45
2007/09/01,331810,69
2007/08/16,476207,93
2007/08/01,429924,29
2007/07/16,527384,77
2007/07/01,565151,76
2007/06/16,393194,41
2007/06/01,836393,05
2007/05/16,232897,25
2007/05/02,430374,81
2007/04/16,405105,63
2007/04/01,622780,93
2007/03/16,876763,85
2007/03/01,742425,61
2007/02/16,277859,95
2007/02/01,769925,56
2007/01/16,838739,55
2006/12/30,778584,07
2006/12/16,147977,45
2006/12/01,270052,12
2006/11/16,562856,94
2006/11/01,910957,29
2006/10/16,264825,58
2006/10/01,952335,92
2006/09/16,217948,41
2006/09/01,381761,44
2006/08/16,977486,91
2006/08/01,238654,88
2006/07/16,512434,48
2006/07/01,952890,65
2006/06/16,100935,17
2006/06/01,810850,99
2006/05/16,100344,71
2006/05/02,024554,27
2006/04/16,038564,49
2006/04/01,738365,95
2006/03/16,936177,30
2006/03/01,582473,43
2006/02/16,317009,66
2006/02/01,412729,87
2006/01/16,432747,79
2005/12/30,492955,94
2005/12/16,449565,86
2005/12/01,388551,17
2005/11/16,742518,80
2005/11/01,970577,98
2005/10/16,041072,71
2005/10/01,766482,24
2005/09/16,214768,10
2005/09/01,316933,17
2005/08/16,475560,68
2005/08/01,961633,26
2005/07/16,477452,13
2005/07/01,009554,87
2005/06/16,793070,44
2005/06/01,176893,35
2005/05/16,867134,97
2005/05/02,772467,43
2005/04/16,119327,10
2005/04/01,815753,69
2005/03/16,196345,03
2005/03/01,800751,93
2005/02/16,816422,53
2005/02/01,540054,34
2005/01/16,335022,08
2004/12/30,168858,28
2004/12/16,479372,17
2004/12/01,504658,69
2004/11/16,754622,64
2004/11/01,185966,23
2004/10/16,355858,62
2004/10/01,110866,66
2004/09/16,923373,59
2004/09/01,096597,70
2004/08/16,335921,59
2004/08/02,868990,45
2004/07/16,205588,25
2004/07/01,312471,66
2004/06/16,208713,87
2004/06/01,614144,72
2004/05/16,589207,13
2004/05/02,653403,91
2004/04/16,705832,12
2004/04/01,196391,62
2004/03/16,615366,69
2004/03/01,697483,50
2004/02/16,698002,00
2004/02/01,216822,77
2004/01/16,731342,96
2003/12/30,739447,64
2003/12/16,177947,87
2003/12/01,991307,78
2003/11/16,238511,68
2003/11/01,941438,47
2003/10/16,305500,03
2003/10/01,912040,43
2003/09/16,600589,53
2003/09/01,187813,92
2003/08/16,354771,00
2003/08/01,766098,91
2003/07/16,679545,75
"""

# โค้ดส่วนนี้ถูกต้องแล้ว
df = pd.read_csv(StringIO(csv_content))
df.columns = ['date', 'six_digit', 'two_digit']

# แปลง 'six_digit' และ 'two_digit' ให้เป็น string แล้วเติมศูนย์นำหน้า
# เนื่องจากข้อมูล 'รางวัลที่ 1' และ 'เลข 2 ตัวล่าง' บางตัวอาจมีศูนย์นำหน้าอยู่แล้ว (เช่น 097863, 06, 00)
# การอ่านเข้ามาเป็น int โดยตรงอาจทำให้ศูนย์นำหน้าหายไป (เช่น 06 จะกลายเป็น 6)
# การแปลงเป็น string แล้ว .zfill() จะช่วยรักษารูปแบบ 6 หลัก และ 2 หลักได้
df['six_digit'] = df['six_digit'].astype(str).str.zfill(6)
df['two_digit'] = df['two_digit'].astype(str).str.zfill(2)

# ทำความสะอาดข้อมูล: ลบแถวที่มีค่าว่าง (NaN) และรีเซ็ต index
df = df.dropna().reset_index(drop=True)

print(df.tail())

           date six_digit two_digit
519  2003/09/16    600589        53
520  2003/09/01    187813        92
521  2003/08/16    354771        00
522  2003/08/01    766098        91
523  2003/07/16    679545        75

In [3]:
df = pd.read_csv(StringIO(csv_content))
df.columns = ['date', 'six_digit', 'two_digit']
df['six_digit'] = df['six_digit'].astype(str).str.zfill(6)
df['two_digit'] = df['two_digit'].astype(str).str.zfill(2)
df = df.dropna().reset_index(drop=True)

# แปลงคอลัมน์ 'date' ให้เป็น datetime object
df['date'] = pd.to_datetime(df['date'])

# **เพิ่มส่วนนี้: เรียงลำดับ DataFrame ตามวันที่จากน้อยไปมาก (เก่าสุดไปใหม่สุด)**
df = df.sort_values(by='date', ascending=True).reset_index(drop=True)

# ฟังก์ชัน extract_features
def extract_features(row_str):
    if not isinstance(row_str, str) or not row_str:
        return {
            'sum_digits': None,
            'has_repeat': None,
            'odd_count': None,
            'even_count': None,
        }
    digits = list(map(int, list(row_str)))
    return {
        'sum_digits': sum(digits),
        'has_repeat': int(len(set(digits)) < len(digits)),
        'odd_count': sum([d % 2 for d in digits]),
        'even_count': sum([1 - d % 2 for d in digits]),
    }

# แยก feature สำหรับ six_digit
features_six_digit = df['six_digit'].apply(lambda x: pd.Series(extract_features(x)))
features_six_digit.columns = [f'six_digit_{col}' for col in features_six_digit.columns]

# แยก feature สำหรับ two_digit
features_two_digit = df['two_digit'].apply(lambda x: pd.Series(extract_features(x)))
features_two_digit.columns = [f'two_digit_{col}' for col in features_two_digit.columns]

# รวมฟีเจอร์ทั้งหมดเข้ากับ DataFrame หลัก
df_feat = pd.concat([df, features_six_digit, features_two_digit], axis=1)

# ตอนนี้ df_feat.tail() จะแสดงงวดล่าสุดคือปี 2025
print("DataFrame พร้อมฟีเจอร์ (8 แถวล่าสุด):")
print(df_feat.tail())

DataFrame พร้อมฟีเจอร์ (8 แถวล่าสุด):
          date six_digit two_digit  six_digit_sum_digits  \
519 2025-04-01    669687        36                    42
520 2025-04-16    266227        85                    25
521 2025-05-02    213388        06                    25
522 2025-05-16    251309        87                    20
523 2025-06-01    559352        20                    29

     six_digit_has_repeat  six_digit_odd_count  six_digit_even_count  \
519                     1                    2                     4
520                     1                    1                     5
521                     1                    3                     3
522                     0                    4                     2
523                     1                    5                     1

     two_digit_sum_digits  two_digit_has_repeat  two_digit_odd_count  \
519                     9                     0                    1
520                    13                     0                    1
521                     6                     0                    0
522                    15                     0                    1
523                     2                     0                    0

     two_digit_even_count
519                     1
520                     1
521                     2
522                     1
523                     2

In [4]:
def extract_features(row):
    digits = list(map(int, list(row)))
    return {
        'sum_digits': sum(digits),
        'has_repeat': int(len(set(digits)) < len(digits)),
        'odd_count': sum([d % 2 for d in digits]),
        'even_count': sum([1 - d % 2 for d in digits]),
    }

features = df['six_digit'].apply(lambda x: pd.Series(extract_features(x)))
df_feat = pd.concat([df, features], axis=1)
df_feat.tail()

,date,six_digit,two_digit,sum_digits,has_repeat,odd_count,even_count
519,2025-04-01,669687,36,42,1,2,4
520,2025-04-16,266227,85,25,1,1,5
521,2025-05-02,213388,06,25,1,3,3
522,2025-05-16,251309,87,20,0,4,2
523,2025-06-01,559352,20,29,1,5,1

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = df_feat[['sum_digits', 'has_repeat', 'odd_count', 'even_count']]
y = df_feat['two_digit'].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False, test_size=0.2)

model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

probs = model.predict_proba(X_test)
classes = model.classes_

top5 = sorted(zip(classes, probs[-1]), key=lambda x: x[1], reverse=True)[:5]
print("🔮 คำทำนาย 2 หลักถัดไป (Top 5):")
for digit, prob in top5:
    print(f" - {str(digit).zfill(2)} | โอกาส: {prob*100:.2f}%")

🔮 คำทำนาย 2 หลักถัดไป (Top 5):
 - 28 | โอกาส: 17.50%
 - 41 | โอกาส: 17.23%
 - 67 | โอกาส: 16.97%
 - 78 | โอกาส: 16.51%
 - 69 | โอกาส: 16.00%

In [6]:
# %% [markdown]
### 📈 เซลล์ที่ 4: Backtest และแสดงผลคำทำนายรวม (6 หลักและ 2 หลัก)

In [7]:
import pandas as pd
from io import StringIO
from sklearn.metrics import accuracy_score
from collections import Counter

# --- 1. เตรียมข้อมูล (จากคำตอบก่อนหน้า) ---
csv_content = """
วันที่,รางวัลที่ 1 (6 หลัก),เลข 2 ตัวล่าง
2025/06/01,559352,20
2025/05/16,251309,87
2025/05/02,213388,06
2025/04/16,266227,85
2025/04/01,669687,36
2025/03/16,757563,32
2025/03/01,818894,54
2025/02/16,847377,50
2025/02/01,558700,51
2025/01/17,807779,23
2025/01/02,730209,51
2024/12/16,097863,21
2024/12/01,669843,61
2024/11/16,187221,38
2024/11/01,536044,32
2024/10/16,482962,00
2024/10/01,718665,59
2024/09/16,608662,37
2024/09/01,199606,94
2024/08/16,095867,28
2024/08/01,407041,46
2024/07/16,367336,21
2024/07/01,434503,89
2024/06/16,518504,31
2024/06/01,530593,42
2024/05/16,205690,60
2024/05/02,980116,17
2024/04/16,943598,79
2024/04/01,803481,90
2024/03/16,997626,78
2024/03/01,253603,79
2024/02/16,941395,43
2024/02/01,607063,09
2024/01/17,105979,61
2023/12/30,625544,89
2023/12/16,356757,85
2023/12/01,251097,91
2023/11/16,557990,14
2023/11/01,743951,63
2023/10/16,931446,44
2023/10/01,727202,66
2023/09/16,320812,46
2023/09/01,915478,91
2023/08/16,471782,67
2023/08/01,407041,46
2023/07/31,260453,11
2023/07/16,169530,62
2023/07/01,922605,16
2023/06/16,264872,30
2023/06/01,125272,09
2023/05/16,132903,99
2023/05/02,843019,65
2023/04/16,984906,71
2023/04/01,087907,99
2023/03/16,025873,73
2023/03/01,417652,55
2023/02/16,590417,80
2023/02/01,297411,92
2023/01/17,812519,47
2022/12/30,157196,58
2022/12/16,845093,14
2022/12/01,375805,08
2022/11/16,121789,64
2022/11/01,913106,70
2022/10/16,613106,15
2022/10/01,484669,50
2022/09/16,943703,75
2022/09/01,929332,83
2022/08/16,331583,42
2022/08/01,436594,14
2022/07/16,620405,53
2022/07/01,981417,61
2022/06/16,361807,92
2022/06/01,319196,02
2022/05/16,155012,06
2022/05/02,658642,09
2022/04/16,395919,58
2022/04/01,970618,10
2022/03/16,737867,03
2022/03/01,061905,07
2022/02/17,098597,57
2022/02/01,944308,30
2022/01/17,880159,92
2021/12/30,819068,36
2021/12/16,639235,83
2021/12/01,077258,82
2021/11/16,032761,57
2021/11/01,045037,95
2021/10/16,386372,38
2021/10/01,578171,83
2021/09/16,070935,90
2021/09/01,114475,79
2021/08/16,046750,23
2021/08/01,910261,69
2021/07/16,556725,70
2021/07/01,713517,29
2021/06/16,691861,17
2021/06/01,292972,45
2021/05/16,684579,14
2021/05/02,501272,18
2021/04/16,100787,56
2021/04/01,472270,05
2021/03/16,890422,19
2021/03/01,835538,73
2021/02/16,424603,39
2021/02/01,912307,97
2021/01/17,384395,15
2020/12/30,803628,19
2020/12/16,201303,70
2020/12/01,100994,84
2020/11/16,972661,46
2020/11/01,506404,40
2020/10/16,286051,38
2020/10/01,837893,59
2020/09/16,244083,57
2020/09/01,999997,98
2020/08/16,945811,88
2020/08/01,569391,92
2020/07/16,873286,53
2020/07/01,347258,83
2020/06/16,516967,64
2020/06/01,831567,24
2020/04/01,051095,22
2020/03/16,503446,77
2020/03/01,875938,98
2020/02/16,781403,94
2020/02/01,589227,06
2020/01/17,491774,68
2019/12/30,510541,81
2019/12/16,529924,97
2019/12/01,453522,81
2019/11/16,017223,32
2019/11/01,967375,79
2019/10/16,812564,15
2019/10/01,691197,59
2019/09/16,340388,85
2019/09/01,798787,20
2019/08/16,775476,89
2019/08/01,387006,58
2019/07/15,369765,88
2019/07/01,943647,86
2019/06/16,174055,29
2019/06/01,516461,46
2019/05/16,962526,71
2019/05/02,061324,25
2019/04/16,570331,23
2019/04/01,109767,52
2019/03/16,724628,64
2019/03/01,345650,65
2019/02/16,074824,56
2019/02/01,967134,04
2019/01/17,197079,65
2018/12/30,735867,02
2018/12/16,356564,62
2018/12/01,021840,67
2018/11/16,989903,16
2018/11/01,149840,58
2018/10/16,200515,93
2018/10/01,452643,99
2018/09/16,149760,79
2018/09/01,734510,26
2018/08/16,586117,10
2018/08/01,386602,78
2018/07/16,596324,27
2018/07/01,963623,83
2018/06/16,223131,46
2018/06/01,988117,95
2018/05/16,075629,20
2018/05/02,248038,85
2018/04/16,739229,60
2018/04/01,412073,85
2018/03/16,218559,82
2018/03/02,759415,29
2018/02/16,309915,39
2018/02/01,026853,31
2018/01/17,203823,50
2017/12/30,911234,98
2017/12/16,955596,89
2017/12/01,451005,33
2017/11/16,292391,98
2017/11/01,533726,85
2017/10/16,413494,86
2017/10/01,880714,52
2017/09/16,170143,71
2017/09/01,143224,65
2017/08/16,715431,37
2017/08/01,756519,36
2017/07/16,820327,87
2017/07/01,112360,26
2017/06/16,943142,47
2017/06/01,053630,61
2017/05/16,454891,53
2017/05/02,008656,35
2017/04/16,816729,40
2017/04/01,392785,80
2017/03/16,273863,92
2017/03/01,978453,78
2017/02/16,229116,14
2017/02/01,054672,42
2017/01/17,145157,25
2016/12/30,377712,46
2016/12/16,435286,35
2016/12/01,086069,77
2016/11/16,858383,44
2016/11/01,785438,86
2016/10/16,571947,98
2016/10/01,887102,33
2016/09/16,240650,42
2016/09/01,638684,62
2016/08/16,254004,33
2016/08/01,272932,57
2016/07/16,449764,55
2016/07/01,082460,53
2016/06/16,073816,79
2016/06/01,511825,14
2016/05/16,141737,98
2016/05/02,399459,02
2016/04/16,221609,87
2016/04/01,066720,92
2016/03/16,134918,32
2016/03/01,439686,06
2016/02/16,356364,98
2016/02/01,927800,09
2016/01/17,304371,50
2015/12/30,008217,02
2015/12/17,930255,08
2015/12/01,915350,78
2015/11/16,795283,03
2015/11/01,361211,45
2015/10/16,968630,62
2015/10/01,594825,07
2015/09/16,743148,06
2015/09/01,021094,89
2015/08/16,033363,40
2015/08/01,518677,53
2015/07/16,121507,49
2015/07/01,759049,26
2015/06/16,644742,05
2015/06/02,388881,65
2015/05/16,011421,38
2015/05/02,543466,30
2015/04/16,506260,38
2015/04/01,605704,70
2015/03/16,048151,92
2015/03/01,240237,34
2015/02/16,001864,90
2015/02/01,155537,79
2015/01/16,244351,74
2014/12/30,461704,57
2014/12/16,948354,90
2014/12/01,480449,11
2014/11/16,479804,25
2014/11/01,206608,44
2014/10/16,656409,94
2014/10/01,375615,44
2014/09/16,772269,35
2014/09/01,856763,22
2014/08/16,662842,91
2014/08/01,766391,82
2014/07/16,468728,45
2014/07/01,378477,39
2014/06/16,673920,95
2014/06/01,781198,18
2014/05/16,087523,20
2014/05/02,103297,52
2014/04/16,153406,26
2014/04/01,028866,95
2014/03/16,531404,79
2014/03/01,906318,35
2014/02/16,384245,01
2014/02/01,180149,95
2014/01/16,306902,52
2013/12/30,561072,48
2013/12/16,341767,79
2013/12/01,168795,27
2013/11/16,806925,28
2013/11/01,739804,47
2013/10/16,963289,60
2013/10/01,647882,14
2013/09/16,562684,63
2013/09/01,548123,05
2013/08/16,321327,20
2013/08/01,356435,82
2013/07/16,566996,86
2013/07/01,646905,51
2013/06/16,289673,69
2013/06/01,935489,90
2013/05/16,687125,56
2013/05/02,603458,07
2013/04/16,843846,86
2013/04/01,571688,53
2013/03/16,968433,52
2013/03/01,976241,37
2013/02/16,368257,09
2013/02/01,565566,66
2013/01/16,820981,08
2012/12/30,302358,00
2012/12/16,529524,72
2012/12/01,110443,43
2012/11/16,639500,15
2012/11/01,524694,63
2012/10/16,281343,28
2012/10/01,124025,58
2012/09/16,540143,79
2012/09/01,329997,07
2012/08/16,683877,28
2012/08/01,895590,50
2012/07/16,904050,11
2012/07/01,915900,60
2012/06/16,159373,51
2012/06/01,882727,38
2012/05/16,814418,31
2012/05/02,889501,29
2012/04/16,583470,62
2012/04/01,257562,69
2012/03/16,607064,08
2012/03/01,222518,79
2012/02/16,648684,18
2012/02/01,320605,32
2012/01/16,451445,81
2011/12/30,526402,65
2011/12/16,884178,21
2011/12/01,408147,02
2011/11/16,997777,57
2011/11/01,805540,54
2011/10/16,955756,83
2011/10/01,511052,15
2011/09/16,731198,28
2011/09/01,724533,85
2011/08/16,536960,62
2011/08/01,218756,12
2011/07/16,116556,12
2011/07/01,622953,51
2011/06/16,351276,88
2011/06/01,562370,46
2011/05/16,406417,05
2011/05/02,054136,85
2011/04/16,825988,44
2011/04/01,814931,01
2011/03/16,593331,96
2011/03/01,656037,97
2011/02/16,481746,27
2011/02/01,610089,55
2011/01/16,281062,23
2010/12/30,884112,49
2010/12/16,334380,24
2010/12/01,181752,09
2010/11/16,813993,43
2010/11/01,191100,59
2010/10/16,621377,42
2010/10/01,488372,02
2010/09/16,017422,66
2010/09/01,354656,11
2010/08/16,911097,64
2010/08/01,210008,10
2010/07/16,180387,34
2010/07/01,480239,68
2010/06/16,500104,73
2010/06/01,444874,81
2010/05/16,480012,12
2010/05/02,360371,06
2010/04/16,211743,96
2010/04/01,959517,22
2010/03/16,364222,97
2010/03/01,215227,97
2010/02/16,133707,03
2010/02/01,186312,14
2010/01/16,073577,67
2009/12/30,994304,87
2009/12/16,685141,05
2009/12/01,776980,59
2009/11/16,055986,58
2009/11/01,689140,85
2009/10/16,258487,00
2009/10/01,169387,06
2009/09/16,202912,48
2009/09/01,015865,32
2009/08/16,462933,96
2009/08/01,154986,92
2009/07/16,000816,94
2009/07/01,207542,66
2009/06/16,930456,15
2009/06/01,777661,26
2009/05/16,111411,54
2009/05/02,294452,11
2009/04/16,368415,33
2009/04/01,816578,50
2009/03/16,268812,36
2009/03/01,553091,67
2009/02/16,038730,93
2009/02/01,534533,69
2009/01/16,743212,25
2008/12/30,218596,22
2008/12/16,074114,25
2008/12/01,205434,05
2008/11/16,002612,20
2008/11/01,272028,76
2008/10/16,431277,98
2008/10/01,882911,67
2008/09/16,012377,56
2008/09/01,695993,09
2008/08/16,380377,36
2008/08/01,850348,11
2008/07/16,257374,41
2008/07/01,943671,50
2008/06/16,729111,75
2008/06/01,414875,35
2008/05/16,329231,69
2008/05/02,453011,62
2008/04/16,982800,64
2008/04/01,012653,71
2008/03/16,074946,33
2008/03/01,936685,05
2008/02/16,137054,80
2008/02/01,212684,26
2008/01/16,556010,81
2007/12/30,595411,81
2007/12/16,513501,96
2007/12/01,113410,18
2007/11/16,562481,73
2007/11/01,927907,88
2007/10/16,032988,48
2007/10/01,430667,76
2007/09/16,499336,45
2007/09/01,331810,69
2007/08/16,476207,93
2007/08/01,429924,29
2007/07/16,527384,77
2007/07/01,565151,76
2007/06/16,393194,41
2007/06/01,836393,05
2007/05/16,232897,25
2007/05/02,430374,81
2007/04/16,405105,63
2007/04/01,622780,93
2007/03/16,876763,85
2007/03/01,742425,61
2007/02/16,277859,95
2007/02/01,769925,56
2007/01/16,838739,55
2006/12/30,778584,07
2006/12/16,147977,45
2006/12/01,270052,12
2006/11/16,562856,94
2006/11/01,910957,29
2006/10/16,264825,58
2006/10/01,952335,92
2006/09/16,217948,41
2006/09/01,381761,44
2006/08/16,977486,91
2006/08/01,238654,88
2006/07/16,512434,48
2006/07/01,952890,65
2006/06/16,100935,17
2006/06/01,810850,99
2006/05/16,100344,71
2006/05/02,024554,27
2006/04/16,038564,49
2006/04/01,738365,95
2006/03/16,936177,30
2006/03/01,582473,43
2006/02/16,317009,66
2006/02/01,412729,87
2006/01/16,432747,79
2005/12/30,492955,94
2005/12/16,449565,86
2005/12/01,388551,17
2005/11/16,742518,80
2005/11/01,970577,98
2005/10/16,041072,71
2005/10/01,766482,24
2005/09/16,214768,10
2005/09/01,316933,17
2005/08/16,475560,68
2005/08/01,961633,26
2005/07/16,477452,13
2005/07/01,009554,87
2005/06/16,793070,44
2005/06/01,176893,35
2005/05/16,867134,97
2005/05/02,772467,43
2005/04/16,119327,10
2005/04/01,815753,69
2005/03/16,196345,03
2005/03/01,800751,93
2005/02/16,816422,53
2005/02/01,540054,34
2005/01/16,335022,08
2004/12/30,168858,28
2004/12/16,479372,17
2004/12/01,504658,69
2004/11/16,754622,64
2004/11/01,185966,23
2004/10/16,355858,62
2004/10/01,110866,66
2004/09/16,923373,59
2004/09/01,096597,70
2004/08/16,335921,59
2004/08/02,868990,45
2004/07/16,205588,25
2004/07/01,312471,66
2004/06/16,208713,87
2004/06/01,614144,72
2004/05/16,589207,13
2004/05/02,653403,91
2004/04/16,705832,12
2004/04/01,196391,62
2004/03/16,615366,69
2004/03/01,697483,50
2004/02/16,698002,00
2004/02/01,216822,77
2004/01/16,731342,96
2003/12/30,739447,64
2003/12/16,177947,87
2003/12/01,991307,78
2003/11/16,238511,68
2003/11/01,941438,47
2003/10/16,305500,03
2003/10/01,912040,43
2003/09/16,600589,53
2003/09/01,187813,92
2003/08/16,354771,00
2003/08/01,766098,91
2003/07/16,679545,75
"""

df = pd.read_csv(StringIO(csv_content))
df.columns = ['date', 'six_digit', 'two_digit']
df['six_digit'] = df['six_digit'].astype(str).str.zfill(6)
df['two_digit'] = df['two_digit'].astype(str).str.zfill(2)
df = df.dropna().reset_index(drop=True)

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by='date', ascending=True).reset_index(drop=True)

def extract_features(row_str):
    if not isinstance(row_str, str) or not row_str:
        return {
            'sum_digits': None,
            'has_repeat': None,
            'odd_count': None,
            'even_count': None,
        }
    digits = list(map(int, list(row_str)))
    return {
        'sum_digits': sum(digits),
        'has_repeat': int(len(set(digits)) < len(digits)),
        'odd_count': sum([d % 2 for d in digits]),
        'even_count': sum([1 - d % 2 for d in digits]),
    }

features_six_digit = df['six_digit'].apply(lambda x: pd.Series(extract_features(x)))
features_six_digit.columns = [f'six_digit_{col}' for col in features_six_digit.columns]

features_two_digit = df['two_digit'].apply(lambda x: pd.Series(extract_features(x)))
features_two_digit.columns = [f'two_digit_{col}' for col in features_two_digit.columns]

df_feat = pd.concat([df, features_six_digit, features_two_digit], axis=1)

print("DataFrame พร้อมฟีเจอร์ (5 แถวล่าสุด):")
print(df_feat.tail())


# --- 2. สร้าง/ปรับปรุงฟังก์ชัน predict_next_lotto ---
def predict_next_lotto(history_df, num_predictions=4):
    """
    ฟังก์ชันสำหรับการทำนายเลขรางวัลที่ 1 (6 หลัก) และเลข 2 ตัวล่าง
    สำหรับงวดถัดไป โดยอิงจากข้อมูลในอดีต (history_df)

    - ทำนายเลข 2 ตัวล่าง: หาเลขที่ออกบ่อยที่สุดในประวัติ (top num_predictions)
    - ทำนายเลข 6 หลัก: เป็นการทำนายที่ซับซ้อนกว่า ต้องใช้ heuristic หรือโมเดล
      ในตัวอย่างนี้จะลองคาดการณ์จากหลักสุดท้ายของเลขที่ออกบ่อย หรือใช้เลขล่าสุด
      (ยังคงเป็นตัวอย่างง่ายๆ ควรปรับปรุงให้ซับซ้อนขึ้น)
    """
    if history_df.empty:
        return None

    # --- การทำนายเลข 2 ตัวล่าง ---
    two_digit_counts = Counter(history_df['two_digit'])
    # ได้เลข 2 ตัวที่ออกบ่อยที่สุด num_predictions อันดับ
    top_n_2digits = two_digit_counts.most_common(num_predictions)
    predicted_2digits = [num for num, count in top_n_2digits]
    # หากมีจำนวนการทำนายไม่ครบ 4 ให้เติมเลขที่เหลือจาก Top 5
    while len(predicted_2digits) < num_predictions and len(two_digit_counts.most_common(5)) > len(predicted_2digits):
        # ดึงเลขที่ไม่ซ้ำกันที่ยังไม่ได้อยู่ใน predicted_2digits
        for num, count in two_digit_counts.most_common(5):
            if num not in predicted_2digits:
                predicted_2digits.append(num)
                if len(predicted_2digits) == num_predictions:
                    break
    # ถ้ายังไม่ครบ ให้เติมด้วยเลขสุ่มหรือค่าเริ่มต้น
    while len(predicted_2digits) < num_predictions:
        predicted_2digits.append(f"{len(predicted_2digits)*10:02d}") # ตัวอย่าง: 00, 10, 20, 30

    # เลือกเลข 2 ตัวหลักสำหรับการ backtest (ตัวที่ออกบ่อยที่สุด)
    main_predicted_2digit = top_n_2digits[0][0] if top_n_2digits else "00"

    # --- การทำนายเลข 6 หลัก ---
    # สำหรับการทำนายเลข 6 หลักจริง ๆ ต้องใช้โมเดลที่ซับซ้อนกว่านี้มาก
    # ในที่นี้ จะลองใช้หลักท้ายสุดที่พบบ่อย (เป็นตัวอย่างเท่านั้น)
    all_last_digits_six = [d[-1] for d in history_df['six_digit'].astype(str)]
    last_digit_six_counts = Counter(all_last_digits_six)
    most_common_last_digit_six = last_digit_six_counts.most_common(1)[0][0] if last_digit_six_counts else '0'

    # สมมติฐานง่ายๆ: เลข 6 หลักอาจจะใกล้เคียงกับเลข 6 หลักงวดล่าสุด แต่ปรับหลักสุดท้าย
    # หรืออาจจะใช้ค่าเฉลี่ย/ค่ากลางของ sum_digits ในช่วงนั้นมาสร้างเลข
    # นี่เป็นเพียง Placeholder ที่ง่ายมากๆ
    predicted_6digit = history_df.iloc[-1]['six_digit'] # ใช้เลข 6 หลักของงวดล่าสุดในประวัติ
    # หรือจะลองปรับแก้หลักสุดท้าย
    # predicted_6digit = predicted_6digit[:-1] + most_common_last_digit_six # ตัวอย่าง
    predicted_6digit = str(predicted_6digit).zfill(6) # ตรวจสอบรูปแบบ

    return {
        "predicted_6digit": predicted_6digit,
        "predicted_2digit": main_predicted_2digit, # เลข 2 ตัวหลักสำหรับการเปรียบเทียบใน backtest
        "top5_2digit": predicted_2digits, # 4 ชุดตัวเลขที่คุณต้องการ (ตอนนี้ตั้งชื่อเป็น top5_2digit)
        "all_predicted_2digits_options": predicted_2digits # ชื่อที่ชัดเจนกว่าสำหรับ 4 ชุด
    }


# --- 3. ฟังก์ชัน backtest_prediction_accuracy ---
def backtest_prediction_accuracy(data_df, predict_fn, window_size=6):
    print(f"\n📊 เริ่มทดสอบย้อนหลัง {len(data_df)} งวด โดยใช้ window ขนาด {window_size}...\n")
    total_tests = 0
    correct_2digit = 0
    correct_3last = 0
    # ตัวแปรสำหรับนับว่าอยู่ใน 4 ชุดทำนายหรือไม่
    correct_2digit_in_multi_options = 0

    # วนลูปเพื่อ backtest
    # เริ่มจาก window_size ไปจนถึงก่อนงวดสุดท้าย (len(data_df))
    # เพราะ 'actual' คือ data_df.iloc[i] ซึ่งเป็นงวดถัดไปที่ต้องทำนาย
    for i in range(window_size, len(data_df)):
        history = data_df.iloc[i - window_size : i] # ประวัติ
        actual = data_df.iloc[i]                   # ผลลัพธ์จริงของงวดที่กำลังทดสอบ

        prediction = predict_fn(history, num_predictions=4) # เรียกใช้ predict_fn พร้อมระบุ 4 ชุดทำนาย

        if prediction is None:
            continue

        pred_6digit = str(prediction.get("predicted_6digit", "")).zfill(6)
        pred_2digit_main = str(prediction.get("predicted_2digit", "")).zfill(2) # เลข 2 ตัวหลัก
        # ดึง 4 ชุดตัวเลขที่ทำนายออกมา
        predicted_2digits_options = [str(t).zfill(2) for t in prediction.get("all_predicted_2digits_options", [])]

        actual_6 = str(actual['six_digit']).zfill(6)
        actual_2 = str(actual['two_digit']).zfill(2)

        # ตรวจสอบความถูกต้อง (สำหรับ backtest จะเทียบกับเลข 2 ตัวหลัก)
        if pred_2digit_main == actual_2:
            correct_2digit += 1

        # ตรวจสอบว่าเลข 2 ตัวจริงอยู่ใน 4 ชุดทำนายหรือไม่
        if actual_2 in predicted_2digits_options:
            correct_2digit_in_multi_options += 1

        if len(pred_6digit) >= 3 and actual_6[-3:] == pred_6digit[-3:]:
            correct_3last += 1

        total_tests += 1

    if total_tests == 0:
        print("❌ ไม่สามารถทำการทดสอบย้อนหลังได้ เนื่องจากข้อมูลไม่เพียงพอ หรือการทำนายคืนค่า None.")
        return

    print(f"✅ จำนวนงวดที่ใช้ทดสอบ: {total_tests}")
    print(f"🎯 ตรง 2 หลักท้ายเป๊ะ (เลขเดี่ยวที่ทำนาย): {correct_2digit} ({correct_2digit/total_tests*100:.2f}%)")
    print(f"🎯 อยู่ใน 4 ชุดเลข 2 หลักที่ทำนาย: {correct_2digit_in_multi_options} ({correct_2digit_in_multi_options/total_tests*100:.2f}%)")
    print(f"🎯 ตรงท้าย 3 หลักของรางวัลที่ 1: {correct_3last} ({correct_3last/total_tests*100:.2f}%)\n")


# --- 4. เรียกใช้งาน ---

# 1. ทำการ Backtest ด้วยข้อมูลทั้งหมดที่มี
# ในที่นี้ data_df จะเป็น df_feat ซึ่งเรียงจากเก่าไปใหม่แล้ว
# 'predict_next_lotto' จะทำนายงวดถัดไปจาก 'history' ที่ป้อนให้
backtest_prediction_accuracy(data_df=df_feat, predict_fn=predict_next_lotto)


# 2. ทำนายงวดถัดไป **ในอนาคต** จากข้อมูลทั้งหมดที่เรามีอยู่แล้ว
print("🔮 ทำนายงวดถัดไป (ในอนาคต) จากข้อมูลล่าสุดทั้งหมด:")
# ส่งข้อมูลทั้งหมด (df_feat) เข้าไปเป็น history
# เพื่อให้ฟังก์ชันใช้ข้อมูลล่าสุดทั้งหมดในการทำนาย 'งวดถัดไป'
final_prediction = predict_next_lotto(df_feat, num_predictions=4)

if final_prediction:
    print(f"\n🎯 เลข 6 หลักที่คาดการณ์: {str(final_prediction['predicted_6digit']).zfill(6)}")
    print("\n📋 4 ชุดเลข 2 หลักที่แนะนำ:")
    for idx, option in enumerate(final_prediction['all_predicted_2digits_options']):
        print(f"  - {str(option).zfill(2)} | ชุดที่ {idx+1}")
else:
    print("❌ ไม่สามารถทำนายได้ เนื่องจากข้อมูลไม่พอ")

DataFrame พร้อมฟีเจอร์ (5 แถวล่าสุด):
          date six_digit two_digit  six_digit_sum_digits  \
519 2025-04-01    669687        36                    42
520 2025-04-16    266227        85                    25
521 2025-05-02    213388        06                    25
522 2025-05-16    251309        87                    20
523 2025-06-01    559352        20                    29

     six_digit_has_repeat  six_digit_odd_count  six_digit_even_count  \
519                     1                    2                     4
520                     1                    1                     5
521                     1                    3                     3
522                     0                    4                     2
523                     1                    5                     1

     two_digit_sum_digits  two_digit_has_repeat  two_digit_odd_count  \
519                     9                     0                    1
520                    13                     0                    1
521                     6                     0                    0
522                    15                     0                    1
523                     2                     0                    0

     two_digit_even_count
519                     1
520                     1
521                     2
522                     1
523                     2

📊 เริ่มทดสอบย้อนหลัง 524 งวด โดยใช้ window ขนาด 6...

✅ จำนวนงวดที่ใช้ทดสอบ: 518
🎯 ตรง 2 หลักท้ายเป๊ะ (เลขเดี่ยวที่ทำนาย): 7 (1.35%)
🎯 อยู่ใน 4 ชุดเลข 2 หลักที่ทำนาย: 20 (3.86%)
🎯 ตรงท้าย 3 หลักของรางวัลที่ 1: 1 (0.19%)

🔮 ทำนายงวดถัดไป (ในอนาคต) จากข้อมูลล่าสุดทั้งหมด:

🎯 เลข 6 หลักที่คาดการณ์: 559352

📋 4 ชุดเลข 2 หลักที่แนะนำ:
  - 79 | ชุดที่ 1
  - 92 | ชุดที่ 2
  - 85 | ชุดที่ 3
  - 69 | ชุดที่ 4

In [8]:
# %% [markdown]
# 📌 เซลล์ที่ 5: คัดกรองเลขท้าย 3 ตัวจากรางวัลที่ 1 และวิเคราะห์ความถี่

# %%
from collections import Counter

# ตรวจสอบว่าคอลัมน์ six_digit มีอยู่ใน data หรือไม่
if 'six_digit' not in df.columns:
    raise ValueError("ไม่พบคอลัมน์ 'six_digit' กรุณาตรวจสอบว่าโหลดข้อมูลมาอย่างถูกต้อง")

# ดึงเลขท้าย 3 หลักจากเลขหกหลัก
df['last3'] = df['six_digit'].str[-3:]

# นับความถี่ของเลขท้าย 3 ตัว
last3_counter = Counter(df['last3'])
top_last3 = last3_counter.most_common(10)

# แสดงผล
print("🔍 Top 10 เลขท้ายสามตัวของรางวัลที่ 1 ที่ออกบ่อยที่สุด:")
for i, (num, freq) in enumerate(top_last3, 1):
    print(f"{i:>2}. เลข: {num} — จำนวน: {freq} ครั้ง")

# ตัวอย่างการคัดเลขท้าย 3 ตัวที่ออกซ้ำมากกว่า 2 ครั้ง
frequent_last3 = [num for num, count in last3_counter.items() if count >= 2]
print("\n📌 เลขท้าย 3 ตัวที่เคยออกมากกว่า 2 ครั้ง:", frequent_last3)

🔍 Top 10 เลขท้ายสามตัวของรางวัลที่ 1 ที่ออกบ่อยที่สุด:
 1. เลข: 391 — จำนวน: 4 ครั้ง
 2. เลข: 684 — จำนวน: 4 ครั้ง
 3. เลข: 377 — จำนวน: 4 ครั้ง
 4. เลข: 372 — จำนวน: 3 ครั้ง
 5. เลข: 422 — จำนวน: 3 ครั้ง
 6. เลข: 327 — จำนวน: 3 ครั้ง
 7. เลข: 564 — จำนวน: 3 ครั้ง
 8. เลข: 825 — จำนวน: 3 ครั้ง
 9. เลข: 411 — จำนวน: 3 ครั้ง
10. เลข: 227 — จำนวน: 3 ครั้ง

📌 เลขท้าย 3 ตัวที่เคยออกมากกว่า 2 ครั้ง: ['500', '438', '307', '947', '391', '403', '207', '990', '597', '373', '866', '858', '372', '054', '422', '327', '134', '893', '554', '452', '933', '072', '577', '518', '729', '564', '935', '434', '761', '825', '052', '925', '763', '374', '151', '924', '336', '988', '907', '481', '501', '411', '684', '800', '377', '993', '596', '533', '812', '415', '661', '816', '986', '387', '227', '517', '371', '012', '097', '656', '037', '331', '417', '756', '198', '605', '997', '143', '905', '804', '767', '404', '704', '630', '650', '286', '116', '453', '863', '519', '117', '324', '840', '903', '867', '628', '787', '388', '446', '258', '395', '603', '272', '196', '106', '041']